app:
  name: quiz-service
  environment: development
  api_key: your-api-key-here

server:
  port: 8080
  read_timeout: 10
  write_timeout: 10
  shutdown_timeout: 10

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: quiz_db
  ssl_mode: disable 