version: '3.8'

services:
  quiz-service:
    build:
      context: ../..
      dockerfile: cmd/quiz/Dockerfile
      target: production
    container_name: quiz-service-prod
    restart: always
    ports:
      - "8082:8080"
    environment:
      - APP_API_KEY=${APP_API_KEY:-prod-api-key}
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=${POSTGRES_DB:-quiz_db}
      - API_KEY=${API_KEY:-prod-api-key}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-prod
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-quiz_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh

volumes:
  postgres_data: 