version: '3.8'

services:
  quiz-api:
    build:
      context: ../..
      dockerfile: cmd/quiz/Dockerfile
    container_name: quiz-api
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - quiz-db
    environment:
      - DB_HOST=quiz-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=quiz_db
      - DB_PORT=5432
      - APP_ENVIRONMENT=development
      - APP_API_KEY=your-secure-api-key
    volumes:
      - ./config:/app/config
    networks:
      - quiz-network

  quiz-db:
    image: postgres:15-alpine
    container_name: quiz-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_db
    volumes:
      - quiz-db-data:/var/lib/postgresql/data
    networks:
      - quiz-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: quiz-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nosmo.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - quiz-db
    networks:
      - quiz-network

volumes:
  quiz-db-data:
  pgadmin-data:

networks:
  quiz-network:
    driver: bridge 