server:
  name: "Telegram Bot Service"
  port: ${SERVER_PORT}
  uploadLimit: 10
  cors:
    allowOrigins:
      - "*"
    allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowHeaders:
      - Origin
      - Content-Type
      - Accept
      - Authorization
    allowCredentials: true
    exposeHeaders:
      - Content-Length
    maxAge: 12h

mongodb:
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT}
  database: ${MONGODB_DATABASE}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}

app:
  api_key: ${APP_API_KEY} 